### ISSUE TITLE
Remove reliance on X/Twitter

### ISSUE THREAD

**Issue by cyber199** [cheerlights/cheerlights-telegram#1]
So I noticed the official Telegram bot found at @CheerLight_Bot was no longer working.  It will fetch the current colour, but won't set a new colour.  Looking at the code here it seems that all it does is make a post on Twitter with some account (presumably the official Cheerlights account).  With the changes to the API made during the transition to X that seem to have resulted in the main way to interact with Cheerlights becoming Discord, I am assuming this reliance on posting to X is the reason why it is broken.

I am unlikely to make a Discord account in the foreseeable future, so it would be nice if the Telegram bot could be made to function independently of other services.  My Python is rusty, so I may not be able to aid with the code, but if I can donate or help in other ways I am willing to.

**Comment by nothans** [comment]
I am checking on this issue. The repo code might be outdated but there is no reliance on Twitter anymore. There were updates on Telegram yesterday. Have you tried the bot today? Thanks for letting us know.

**Comment by cyber199** [comment]
Still seems not happy.  Even sending a `/help` to the bot seems to not have a response now.

**Comment by n8acl** [comment]
The code here is very outdated. The bot was just updated over the weekend using a different library and twitter was removed a while ago. The bot is working. To invoke the bot use /start.
